// pages/projects/index.vue
<template>
<main class="normal-page">
    <h1>Minecraft Mods</h1>
    
    <div class="project-list">
        <ProjectCard
          v-for="[slug, mod] in Object.entries(xanderMods)"
          :slug="slug"
          :title="mod.title"
          :summary="mod.summary ?? mrProjects[slug].description"
          :icon="mod.icon ?? mrProjects[slug]?.icon_url ?? ``"
          :tags="mod.tags"
          :featured="mod.featured"/>
    </div>
</main>

</template>

<script setup lang="ts">
const mrProjects = await useModrinthProjects()

</script>

<style scoped lang="scss">
.project-list {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(20rem, 1fr));
    gap: 1rem;
}

</style>

// src/app/projects/page.tsx
import { projects } from "./projects"
import { ProjectCardFromProject } from "../ui/project/ProjectCard"

export default function Page() {
    return (
        <main className="normal-page">
            <h1>My Projects</h1>

            <div className="grid [grid-template-columns:repeat(auto-fill,minmax(20rem,1fr))] gap-4">
                <ProjectList />
            </div>
        </main>
    )
}

function ProjectList() {
    return Object.entries(projects).map(([slug, project]) => (
        <ProjectCardFromProject project={project} slug={slug} key={slug} />
    ))
}
