// components/Button.vue
<template>
    <NuxtLink 
      v-if="props.to"
      :to="props.to"
      class="container">
        <slot/>
    </NuxtLink>

    <button 
      v-else-if="props.action"
      @click="props.action"
      class="container">
        <slot/>
    </button>    
</template>

<script setup lang="ts">
const props = defineProps({
    to: {
        type: String,
        default: null
    },
    action: {
        type: Function,
        default: null
    }
})
</script>

<style scoped lang="scss">
.container {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: row;
}
</style>

// src/app/ui/Button.tsx
import Link from "next/link"

export type ButtonProps = {
    href?: string,
    action?: () => void,
    children: React.ReactNode,
    className?: string,
}

export default function Button({
    href, action, children, className,
}: ButtonProps) {
    if (href) {
        return (
            <Link
                href={href}
                className={`flex justify-center items-center flex-row ${className}`}
            >{children}</Link>
        )
    } else if (action) {
        return (
            <button
                onClick={action}
                className={`flex justify-center items-center flex-row ${className}`}
            >{children}</button>
        )
    }
}
