// src/app/ui/CurrentTIme.tsx
'use client'

import { useEffect, useState } from "react";

export type CurrentTimeProps = {
    timezone: string,
    format: "short" | "medium" | "long" | "full",
    hour12: boolean
}

export default function CurrentTime({
    timezone, format = "short", hour12 = true
} : CurrentTimeProps) {
    const timeGetter = () => {
        const date = new Date()
        return date.toLocaleTimeString('en-US', { timeZone: timezone, timeStyle: format, hour12: hour12 })
    }

    const [time, setTime] = useState(timeGetter());

    useEffect(() => {
        const intervalId = setInterval(() => setTime(timeGetter()), 1000)
        return () => clearInterval(intervalId)
    })

    return <code>{time}</code>
}

// components/content/CurrentTime.vue
<template>
    <code>{{ time }}</code>
</template>

<script setup lang="ts">
const props = defineProps({
    format: {
        type: String,
        default: "short"
    },
    timezone: {
        type: String,
        required: false
    }
})

const time = ref("")

function updateTime() {
    const date = new Date()
    time.value = date.toLocaleTimeString("en-US", { timeZone: props.timezone, timeStyle: props.format as any, hour12: true })
}
updateTime()

let timer: NodeJS.Timeout
onMounted(() => {
    timer = setInterval(updateTime, 1000)
})

onBeforeUnmount(() => {
    clearInterval(timer)
})
</script>
