// src/app/ui/YoutubeEmbed.tsx
import styles from "./YoutubeEmbed.module.scss"

export default function YoutubeEmbed({
    video
} : {
    video: string
}) {
    return (
        <div className={styles.youtube}>
            <iframe 
                src={`https://www.youtube.com/embed/${video}`} 
                title="Youtube video player"
                allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                allowFullScreen
            />
        </div>
    )
}

// components/content/YoutubeEmbed.vue
<template>
    <iframe width="560" height="315" :src="'https://www.youtube.com/embed/' + video"
        title="YouTube video player" frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen></iframe>
</template>

<script setup lang="ts">
const props = defineProps<{
    video: string
}>()
</script>
