// src/app/projects/[id]/page.tsx
import { notFound } from "next/navigation"
import { CurseforgeMod, ModrinthMod, fetchCurseforgeProject, fetchModrinthProject } from "@/app/lib/publishers"
import { Project, projects } from "../projects"
import Image from "next/image"
import Button from "@/app/ui/Button"
import { serialize } from 'next-mdx-remote/serialize'
import ClientMDXRemote from "./ClientMDXRemote"
import GallerySection from "./Gallery"
import { Metadata, ResolvingMetadata } from "next"

type PageProps = {
    params: Promise<{ id: string }>
}

export type ProjectInfo = {
    local: Project,
    modrinth?: ModrinthMod,
    curseforge?: CurseforgeMod,
}

export type SectionProps = {
    project: ProjectInfo
}

export async function generateStaticParams() {
    return Object.keys(projects).map(slug => ({
        id: slug
    }))
}

export async function generateMetadata(props: PageProps, parent: ResolvingMetadata): Promise<Metadata> {
    const params = await props.params;
    const local = projects[params.id]

    const title = `${local.title} - Minecraft Mod`
    const description = `${local.summary} - Download the Minecraft Mod ${local.title} by isXander`
    return {
        title,
        description,
        openGraph: {
            title,
            description,
            images: local.icon?.src
        },
        robots: 'all'
    }
}

export default async function ProjectPage(props: PageProps) {
    const params = await props.params;
    const local: Project | undefined = projects[params.id]

    const project: ProjectInfo = {
        local,
        modrinth: local?.sites?.mr ? await fetchModrinthProject(local.sites.mr) : undefined,
        curseforge: local?.sites?.cf ? await fetchCurseforgeProject(local.sites.cf) : undefined,
    }

    if (!local) {
        return notFound()
    }

    return (
        <main>
            <HeroSection project={project} />
            <BodySection project={project} />
            <GallerySection gallery={project.modrinth?.gallery} />
        </main>
    )
}

function HeroSection({
    project: { local, modrinth, curseforge }
}: SectionProps) {
    const backdropImage = local.backdropImage?.src ?? modrinth?.gallery?.find(image => image.featured)?.url

    return (
        <section className="py-8 min-h-[75vh] relative flex flex-col items-center justify-between">
            <div
                className="absolute left-0 right-0 bottom-0 -top-16 -z-10 bg-cover bg-center w-full h-[calc(100%+4rem)]"
                style={{
                    backgroundImage: `linear-gradient(to bottom, rgba(0, 0, 0, 0.2), rgba(34, 34, 34, 1.0)), url(${backdropImage ?? ''})`
                }}
            />

            <div>
                <div className="flex flex-row items-center justify-center gap-4 mx-4 max-[750px]:flex-col">
                    {local.icon ? (
                        <Image
                            src={local.icon!}
                            alt="Project icon"
                            className="h-24 w-auto rounded-[25%] max-[750px]:h-16 max-[430px]:h-12"
                        />
                    ) : (
                        <img
                            src={modrinth?.icon_url}
                            alt="Project icon"
                            className="h-24 w-auto rounded-[25%] max-[750px]:h-16 max-[430px]:h-12"
                        />
                    )}

                    <h1
                        className="wrap-break-word m-0 [text-shadow:2px_2px_2px_black] max-[750px]:text-[3rem] max-[430px]:text-[2.25rem]"
                        dangerouslySetInnerHTML={{ __html: local.title }}
                    />
                </div>

                <h2 className="[text-shadow:2px_2px_2px_black] text-center max-[750px]:text-[1.5rem]">
                    {local.summary ?? modrinth?.description ?? ''}
                </h2>
            </div>

            <div className="flex flex-row items-center gap-6 text-[1.2rem] [&_a]:text-foreground">
                {((local.showDownload ?? true) && (modrinth || curseforge)) ? (
                    <Button
                        href={modrinth
                            ? `https://modrinth.com/mod/${modrinth!.slug}/versions#download`
                            : `https://www.curseforge.com/minecraft/mc-mods/${curseforge!.slug}/files`}
                        className="text-[1.5rem] text-white! bg-primary px-4 py-2 rounded-2xl border-2 border-primary transition-all duration-[250ms] hover:no-underline hover:border-foreground">
                        Download
                    </Button>
                ) : undefined}

                {local.extraHeroButtons?.map((extraButton, idx) => (
                    <Button
                        href={extraButton.link}
                        key={idx}
                        className={extraButton.strong ? "text-[1.5rem] text-white! bg-primary px-4 py-2 rounded-2xl border-2 border-primary transition-all duration-[250ms] hover:no-underline hover:border-foreground" : ''}>
                        {extraButton.text}
                    </Button>
                ))}

                {modrinth || curseforge ? (
                    <h4 className="my-2">
                        { formatNumberMetricUnits((modrinth?.downloads ?? 0) + (curseforge?.downloadCount ?? 0)) } downloads
                    </h4>
                ) : undefined}
            </div>
        </section>
    )
}

async function BodySection({
    project: { local, modrinth, curseforge }
}: SectionProps) {

    let markdown = local.body
    if (!markdown) {
        const mdxSource = await serialize(modrinth!.body)
        markdown = <ClientMDXRemote {...mdxSource} />
    }

    return (
        <section className="markdown-page markdown">
            {markdown}
        </section>
    )
}

function formatNumberMetricUnits(n: number) {
    const ranges = [
        { divider: 1e18, suffix: 'E' },
        { divider: 1e15, suffix: 'P' },
        { divider: 1e12, suffix: 'T' },
        { divider: 1e9, suffix: 'B' },
        { divider: 1e6, suffix: 'M' },
        { divider: 1e3, suffix: 'k' }
    ];

    for (let i = 0; i < ranges.length; i++) {
        if (n >= ranges[i].divider) {
            const decimal = n / ranges[i].divider;
            const suffix = ranges[i].suffix;
            return decimal.toFixed(2) + suffix;
        }
    }
    return n.toString();
}

// pages/mods/[id].vue
<template>
<div class="container">
    <section 
      id="header-section" 
      :style="{ 
        backgroundImage: `linear-gradient(to bottom, rgba(0, 0, 0, 0.2), rgba(34, 34, 34, 1.0)), url(${backdropImage ?? ''})` 
      }">
        <div>
            <div id="title">
                <img :src="mod.icon ?? mrProject.icon_url" alt="project icon" class="title-icon">
                <h1 class="title-h1">{{ mod.title }}</h1>
            </div>

            <h2 class="title-desc">{{ mod.summary ?? mrProject.description }}</h2>
        </div>

        <div id="download-section">
            <Button 
              v-if="mod.downloadReplacement"
              class="download-btn" 
              :to="mod.downloadReplacement.link">
                {{ mod.downloadReplacement.text }}
            </Button>
            <Button 
              v-else-if="mrProject"
              class="download-btn" 
              :to="`https://modrinth.com/mod/${mod.sites!.mr}/versions`">
                Download
            </Button>
            <Button 
              v-else-if="cfProject"
              class="download-btn" 
              :to="`https://www.curseforge.com/minecraft/mc-mods/${cfProject.slug}/files`">
                Download
            </Button>
            
            <h4 v-if="mrProject || cfProject" class="download-count">{{ formatNumberMetricUnits((mrProject.downloads ?? 0) + (cfProject.downloadCount ?? 0)) }} downloads</h4>
        </div>
    </section>

    <section class="body">
        <Markdown v-if="mod.body" :content="mod.body" class="markdown markdown-page"/>
        <Markdown v-else-if="mrProject" :content="mrProject.body" class="markdown markdown-page"/>
        <div v-else class="markdown markdown-page">
            <h1>No body found.</h1>
        </div>
    </section>
</div>

</template>

<script setup lang="ts">
definePageMeta({
    middleware: [
        function(to, from) {
            if ((to.params.id as string) in xanderMods === false) {
                return abortNavigation({
                    statusCode: 404,
                    message: "Mod not found"
                })
            }
        }
    ]
})

const route = useRoute()
const modId = route.params.id as string

const mod = xanderMods[modId]

const mrProject = mod.sites ? await $fetch<ModrinthMod>(`https://api.modrinth.com/v2/project/${mod.sites.mr}`) : null
const cfProject = mod.sites ? (await $fetch<{data: CurseforgeMod}>(`https://api.curse.tools/v1/cf/mods/${mod.sites.cf}`)).data : null

const backdropImage = mod.backdropImage ?? mrProject.gallery.find(image => image.featured === true)?.url

</script>

<style scoped lang="scss">
#header-section {
    background-size: cover;
    padding: 2rem 0;
    min-height: 75vh;

    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-between;

    #title {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: center;
        gap: 1rem;
        margin: 0 1rem;

        .title-h1 {
            word-wrap: break-word;
            margin: 0;
            text-shadow: 2px 2px 2px black;
        }

        .title-icon {
            height: 6rem;
            width: auto;
            border-radius: 25%;
        }
    }

    .title-desc {
        text-shadow: 2px 2px 2px black;
        text-align: center;
    }

    #download-section {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 1rem;
        font-size: 1.2rem;

        .download-btn {
            font-size: 1.5rem;
            color: white;
            background-color: $primary-color;
            padding: 0.5rem 1rem;
            border-radius: 1rem;
            border: 2px solid $primary-color;
            transition: 0.25s;

            &:hover {
                text-decoration: none;
                border-color: $foreground-color;
            }
        }

        .download-count {
            margin: 0.5rem 0;
        }
    }
}



</style>
